name: Find SX Project

on:
  push:
    branches:
      - dev-2

jobs:
  find-sx-project:
    runs-on: ubuntu-latest

    env:
      ENV_NAME: dev-us
      REALMS_MAPPING: .github/env-realms.yaml

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install yq
      uses: mikefarah/yq@v4

    - name: Read SX project and stage from env-realms.yaml
      id: read_sx_project_and_stage
      run: |
        sx_project=$(yq e ".${ENV_NAME}.sx-project" ${REALMS_MAPPING})
        STAGE=$(yq e ".${ENV_NAME}.env-stage" ${REALMS_MAPPING} | tr '[:lower:]' '[:upper:]')
        stage_lower=$(yq e ".${ENV_NAME}.env-stage" ${REALMS_MAPPING} | tr '[:upper:]' '[:lower:]')
        echo "sx_project=${sx_project}"
        echo "STAGE=${STAGE}"
        echo "STAGE_LOWER=${stage_lower}"
        echo "sx_project=${sx_project}" >> $GITHUB_ENV
        echo "STAGE_LOWER=${stage_lower}" >> $GITHUB_ENV
        echo "STAGE=${STAGE}" >> $GITHUB_ENV

    - name: Get Key Vaults
      id: azure-secrets
      uses: BY-Product-Development/ds-shared-actions/azure/azure-key-vault@az-key-vault/1.0
      with:
        key-vault: ${{ env.KEY_VAULT_NAME }}
        secrets: >
          STRATOSPHERE-AUTH-END-POINT=stratosphere-${{ env.STAGE_LOWER }}-auth-end-point

    - name: Create Dynamic Secret Name
      id: set_secret_name
      run: |
        echo "client_id=ST_${{ env.STAGE }}_GITHUB_SERVICE_ACCOUNT_ID" >> "$GITHUB_OUTPUT"
        echo "client_secret=ST_${{ env.STAGE }}_GITHUB_SERVICE_ACCOUNT_SECRET" >> "$GITHUB_OUTPUT"

    - name: Stratopshere access Token
      id: stratosphere-token
      uses: BY-Product-Development/ds-shared-actions/stratosphere/access-token-get@stratosphere-access-token-get-v1.0.1
      with:
        auth-endpoint: ${{ steps.azure-secrets.outputs['STRATOSPHERE-AUTH-END-POINT'] }}
        client-id: ${{ secrets[steps.set_secret_name.outputs.client_id] }}
        client-secret: ${{ secrets[steps.set_secret_name.outputs.client_secret] }}

    - name: Debug environment
      run: env

    - name: Display SX project and stage
      run: |
        echo "The SX project is ${{ env.sx_project }}"
        echo "The environment stage is ${{ env.STAGE }}"
