name: Status Check

on:
  workflow_run:
    workflows: 
      - "realm-onboard"
      - "realm-decommission"
    types:
      - completed

jobs:
  status-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any dependencies your script needs here

      - name: Execute status check script
        run: python .github/workflows/status_check.py
